export const EXAMPLE = 'FILTER';
export const PIE_DATA_LOADING = 'LOADING PIE DATAT CHART';
export const PIE_DATA_LOADED_SUCCESS = 'SUCCESSFULLY LOADED PIE DATA';
export const PIE_DATA_LOADED_FAIL = 'FAILED TO LOAD PIE DATA';
